### ISSUE TITLE
feat: Access Origin by geolocation with 302 redirection

### ISSUE THREAD

**Issue by pahud** [pahud/cdk-cloudfront-plus#11]
After discussing with  @minche-tsai , we are interested to implement the **Access Origin by geolocation** extension.

<img width="1456" alt="圖片" src="https://user-images.githubusercontent.com/278432/112107959-9696b780-8bea-11eb-8de0-83dde5b806a2.png">

### Primary Use Case

1. Dynamically route viewer requests to different S3 buckets in different regions(see this [blog post](https://aws.amazon.com/tw/blogs/networking-and-content-delivery/dynamically-route-viewer-requests-to-any-origin-using-lambdaedge/))

### Other Use Cases
1. Two API Gateways with one in `ap-northeast-1` and the other in `us-west-2` running the same serverless application sharing the same cloudfront distribution. Users visiting the PoP should be routed to nearest origin.
2. One in `cn-north-1` and the other in `ap-northeast-1`, all china clients visiting the global CF edges should go to `cn-north-1` while others `ap-northeas-1`.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by pahud** [comment]
copy @NingLu

**Comment by MinCheTsai** [comment]
Let's GO

**Comment by minche-tsai** [comment]
Let's Go

**Comment by pahud** [comment]
After offline discussion with @minche-tsai and @NingLu , we'll implement the 302 redirection based on viewer country with HTTP origin, not S3 bucket.

https://docs.aws.amazon.com/zh_cn/AmazonCloudFront/latest/DeveloperGuide/lambda-examples.html#lambda-examples-redirect-based-on-country
