### ISSUE TITLE
feat: http302 from origin extension

### ISSUE THREAD

**Issue by pahud** [pahud/cdk-cloudfront-plus#12]
After discussing with @RicoToothless, we are planing to implement a extension construct for [http302 from origin](https://github.com/awslabs/aws-cloudfront-extensions/tree/main/edge/nodejs/http302-from-origin).

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by pahud** [comment]
copy @NingLu

**Comment by RicoToothless** [comment]
on my way
