### ISSUE TITLE
feat: custom log to kinesis firehose

### ISSUE THREAD

**Issue by pahud** [pahud/cdk-cloudfront-plus#14]
Have discussed with @titanjer and we are interested to build a custom extension to pipeline custom log to backend data ingestion service like **Amazon Kinesis Firehose**. The high level API may look like

```ts

const stream = new firehose.CfnDeliveryStream(...);

const extension = new CustomFirehoseLog(scope, id, {
    targetStream: stream,
    includeBody: true,
    requiredHeaders,
});
```

### Use Case

https://aws.amazon.com/tw/blogs/networking-and-content-delivery/global-data-ingestion-with-amazon-cloudfront-and-lambdaedge/

![圖片](https://user-images.githubusercontent.com/278432/112245924-d44c1c80-8c8c-11eb-8095-c3b6469325db.png)

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by titanjer** [comment]
Nice! Lets move on next week! ❤️
