### ISSUE TITLE
feat: authentication against any oauth2 provider

### ISSUE THREAD

**Issue by pahud** [pahud/cdk-cloudfront-plus#17]
Discussed with @dwchiang today and we both agreed to implement an extension for authentication against any oauth2 provider to protect the origin(e.g. s3 bucket).

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by dwchiang** [comment]
Awesome! Let's build it :)

**Comment by pahud** [comment]
Hooray!! 👍
