### ISSUE TITLE
feat: Override request - convert query string

### ISSUE THREAD

**Issue by pahud** [pahud/cdk-cloudfront-plus#23]
Just discussed with  @HsiehShuJeng  and we both agreed to implement the **Convert query string** from [Override Request](https://github.com/awslabs/aws-cloudfront-extensions/blob/main/docs/LambdaEdge.md#override-request).

<img width="1305" alt="圖片" src="https://user-images.githubusercontent.com/278432/112778068-48fccd80-9076-11eb-9538-6cb05c66f5e4.png">

As this extension is not available from SAR, we will build with custom extension fro scratch.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by HsiehShuJeng** [comment]
sounds interesting. Let's get started!

**Comment by pahud** [comment]
After discussing with @HsiehShuJeng , we probably can design our API like this



```ts
new ConvertQueryStringToHeaders(scope, id, {
    // trusted query arguments
    headers: [ 'key1', 'key2' ]
});
```
In this case, requests with query string like `/item?key1=val1&key2=val2&key3=val3` through L@E will inject new headers like

```
X-KEY1: val1
X-KEY2: val2
```

And we'll not inject `key3` as it's not defined in the `headers` property.

What do you think @HsiehShuJeng ?

Any comments @guan840912 @BabooPan @minche-tsai ?

**Comment by HsiehShuJeng** [comment]
For functional purpose, I agree with an implementation of what you mentioned. If there is a more vivid, or practical scenario, that can be concise, we can consider adding it into this demo stack.

**Comment by HsiehShuJeng** [comment]
@pahud  In the meantime, I also experienced two weird things when building the resources for this extension.
1. creation failure by utilizing `PythonFunction`  in the module of `@aws-cdk/aws-lambda-python` to support the L@E function.
2. creation failure by attempting to reference an OAI resource created in the nested stack in the build of `cf.Distribution` whose scope is at the parent stack. By a trail and error method, for creating with success, you need to reference the OAI resource via `cf.OriginAccessIdentity.fromOriginAccessIdentityName()`.

**Comment by HsiehShuJeng** [comment]
> After discussing with @HsiehShuJeng , we probably can design our API like this
> 
> ```ts
> new ConvertQueryStringToHeaders(scope, id, {
>     // trusted query arguments
>     args: [ 'key1', 'key2' ]
> });
> ```
> 
> In this case, requests with query string like `/item?key1=val1&key2=val2&key3=val3` through L@E will be injected with additional headers like
> 
> ```
> X-KEY1: val1
> X-KEY2: val2
> ```
> 
> No `key3` as it's not defined in the `args` property.
> 
> What do you think @HsiehShuJeng ?
> 
> Any comments @guan840912 @BabooPan @minche-tsai ?

For simplicity and functionality, I agree with this implementation for whitelisting.
