### ISSUE TITLE
 (SO8101)  serving-based-on-device

### ISSUE THREAD

**Issue by pahud** [pahud/cdk-cloudfront-plus#79]
@RicoToothless is going to pick up this extension.

see this applicatoin in [SAR](https://ap-northeast-1.console.aws.amazon.com/lambda/home?region=ap-northeast-1#/create/app?applicationId=arn:aws:serverlessrepo:us-east-1:418289889111:applications/serving-based-on-device).

see https://github.com/pahud/cdk-cloudfront-plus/issues/56#issuecomment-817033218

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by RicoToothless** [comment]
I'm glad to help

**Comment by RicoToothless** [comment]
pending for this issue
https://github.com/awslabs/aws-cloudfront-extensions/issues/112
