### ISSUE TITLE
feat: Default Directory Indexes in Amazon S3-backed Amazon CloudFront Origins

### ISSUE THREAD

**Issue by pahud** [pahud/cdk-cloudfront-plus#9]
I am planning to work with @guan840912 to implement [Default Directory Indexes in Amazon S3-backed Amazon CloudFront Origins](https://aws.amazon.com/tw/blogs/compute/implementing-default-directory-indexes-in-amazon-s3-backed-amazon-cloudfront-origins-using-lambdaedge/).

This extension seems not available in SAR so we will create this from scratch as the Custom extension and eventually contribute to the upstream as part of official SAR extensions.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by guan840912** [comment]
I may be able to implement this feature request

**Comment by pahud** [comment]
Hi @NingLu 

Is this extension already available in SAR or TODO list?

**Comment by ranrotx** [comment]
I would instead implement this using [CloudFront Functions](https://github.com/aws-samples/amazon-cloudfront-functions/tree/main/url-rewrite-single-page-apps) versus Lambda@Edge.
